---
- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

- name: Add redmine User
  user:
    name: redmine
    shell: /usr/sbin/nologin
    home: /data/wwwroot/redmine
    create_home: no

- name: download redmine 
  unarchive:
    src: '{{redmine_download_url}}'
    dest: /data/wwwroot
    remote_src: yes
    validate_certs: no
    owner: redmine
    group: redmine

- name: Get ruby version dir_name
  shell: ls /usr/local/rvm/rubies |grep ruby
  register: ruby_dir_name

- name: Get redmine version 
  shell: ls /data/wwwroot/ |grep redmine |cut -d- -f 2
  register: redmine_version

- name: Rename and Remove warning messages
  shell: |
    mv redmine-*  redmine
    sed -i 's/ruby.*Bundler.*/#&/g' Gemfile
  args:
    chdir: /data/wwwroot
 
- name: set databases config
  copy: 
    src: database.yml
    dest: /data/wwwroot/redmine/config

- name: Additional dependencies
  copy: src=Gemfile.local dest=/data/wwwroot/redmine/
    
- name: bundler install required
  bundler:
    state: present
    chdir: /data/wwwroot/redmine
    extra_args: --without development test rmagick

- name: Session store secret generation
  command: bundle exec rake generate_secret_token
  args:
    chdir: /data/wwwroot/redmine

- name: Database schema objects creation
  shell: RAILS_ENV=production bundle exec rake db:migrate
  args:
    chdir: /data/wwwroot/redmine

- name: Database default data set
  shell: echo '{{redmine_lang}}' | RAILS_ENV=production bundle exec rake redmine:load_default_data 
  args:
    chdir: /data/wwwroot/redmine

- name: make directory
  file:
    path: /data/wwwroot/redmine/{{item}}
    owner: redmine 
    group: redmine
    state: directory
    recurse: yes    
    mode: 755
  with_items:
    - tmp/pdf
    - tmp/pids
    - public/plugin_assets

- name: set redmine service
  template:
    src: redmine.service
    dest: /lib/systemd/system/redmine.service
  
- name: start redmine
  service: name=redmine state=started enabled=yes

- name:  File system permissions
  file: 
    path: /data/wwwroot/redmine
    owner: redmine 
    group: redmine
    state: directory
    recurse: yes

# Check version
- block:
  - name: Check redmine Version
    shell: sudo echo "redmine version:" "{{redmine_version.stdout}}" | sudo tee -a /data/logs/install_version.txt

# check service state
  - name: Check redmine Service
    shell: systemctl status redmine | grep Active*
    register: check_redmine_service
    notify: check_redmine_service