---
- name: Install requirements
  apt:
    name: [libxml2-dev,libmysqlclient-dev,libssl-dev]
  when: ansible_os_family == "Debian"

- name: Add redmine User
  user:
    name: redmine
    shell: /usr/sbin/nologin
    home: /data/wwwroot/redmine
    create_home: no

- name: download redmine 
  unarchive:
    src: '{{redmine_download_url}}'
    dest: /data/wwwroot
    remote_src: yes
    validate_certs: no
    owner: redmine
    group: redmine

- shell: mv /data/wwwroot/redmine-*  /data/wwwroot/redmine

- name: set databases config
  copy: 
    src: database.yml
    dest: /data/wwwroot/redmine/config

#- name: Additional dependencies
#  copy: src=Gemfile.local dest=/data/wwwroot/redmine/

- name: Install dependencies by RedHat
  shell: yum install mysql-devel -y
  when: ansible_os_family == "RedHat"
    
- name: bundler install required
  bundler:
    state: present
    chdir: /data/wwwroot/redmine
    extra_args: --without development test rmagick

- name: Session store secret generation
  command: bundle exec rake generate_secret_token
  args:
    chdir: /data/wwwroot/redmine

- name: Database schema objects creation
  shell: RAILS_ENV=production bundle exec rake db:migrate
  args:
    chdir: /data/wwwroot/redmine

- name: Database default data set
  shell: echo '{{redmine_lang}}' | RAILS_ENV=production bundle exec rake redmine:load_default_data 
  args:
    chdir: /data/wwwroot/redmine

- name: make directory
  file:
    path: /data/wwwroot/redmine/{{item}}
    owner: redmine 
    group: redmine
    state: directory
    recurse: yes    
    mode: 755
  with_items:
    - tmp/pdf
    - tmp/pids
    - public/plugin_assets

- name: set redmine service
  copy:
    src: redmine.service
    dest: /lib/systemd/system/redmine.service

# rvm rvmrc warning ignore allGemfiles 用于消除警告信息
- name: Link  Redmine service 
  shell: |
    ln -sf /usr/local/rvm/gems/ruby-2.4.9/bin/puma /usr/local/bin/
    ln -sf /usr/local/rvm/gems/ruby-2.4.9/bin/ruby_executable_hooks /usr/bin/
    rvm rvmrc warning ignore allGemfiles
  when: ansible_os_family == "RedHat"
  
- name: start redmine
  service: name=redmine state=started enabled=yes

- name:  File system permissions
  file: 
    path: /data/wwwroot/redmine
    owner: redmine 
    group: redmine
    state: directory
    recurse: yes
